---
# Production Environment Inventory

all:
  children:
    directory_services:
      hosts:
        ds-vm-prod:
          ansible_host: ds-prod.example.com
          ansible_user: fradmin
          ds_role: all
    
    access_management:
      hosts:
        am-vm-prod:
          ansible_host: am-prod.example.com
          ansible_user: fradmin
          depends_on:
            - directory_services
    
    identity_management:
      hosts:
        idm-vm-prod:
          ansible_host: openidm-prod.example.com
          ansible_user: fradmin
          depends_on:
            - directory_services
            - access_management
    
    identity_gateway:
      hosts:
        ig-vm-prod:
          ansible_host: platform-prod.example.com
          ansible_user: fradmin
          depends_on:
            - access_management
            - identity_management
    
    platform_ui:
      hosts:
        ui-vm-prod:
          ansible_host: am-prod.example.com
          ansible_user: fradmin
          depends_on:
            - access_management
            - identity_management
            - identity_gateway

  vars:
    ansible_python_interpreter: /usr/bin/python3
    environment: prod
    vault_environment: prod

