---
# Development Environment Inventory

all:
  children:
    directory_services:
      hosts:
        ds-vm-dev:
          ansible_host: ds-dev.example.com
          ansible_user: fradmin
          ds_role: all  # Runs all DS instances (config, cts, idrepo)
    
    access_management:
      hosts:
        am-vm-dev:
          ansible_host: am-dev.example.com
          ansible_user: fradmin
          depends_on:
            - directory_services
    
    identity_management:
      hosts:
        idm-vm-dev:
          ansible_host: openidm-dev.example.com
          ansible_user: fradmin
          depends_on:
            - directory_services
            - access_management
    
    identity_gateway:
      hosts:
        ig-vm-dev:
          ansible_host: platform-dev.example.com
          ansible_user: fradmin
          depends_on:
            - access_management
            - identity_management
    
    platform_ui:
      hosts:
        ui-vm-dev:
          ansible_host: am-dev.example.com  # Usually same VM as AM
          ansible_user: fradmin
          depends_on:
            - access_management
            - identity_management
            - identity_gateway

  vars:
    ansible_python_interpreter: /usr/bin/python3
    environment: dev
    vault_environment: dev

