---
# QA Environment Inventory

all:
  children:
    directory_services:
      hosts:
        ds-vm-qa:
          ansible_host: ds-qa.example.com
          ansible_user: fradmin
          ds_role: all
    
    access_management:
      hosts:
        am-vm-qa:
          ansible_host: am-qa.example.com
          ansible_user: fradmin
          depends_on:
            - directory_services
    
    identity_management:
      hosts:
        idm-vm-qa:
          ansible_host: openidm-qa.example.com
          ansible_user: fradmin
          depends_on:
            - directory_services
            - access_management
    
    identity_gateway:
      hosts:
        ig-vm-qa:
          ansible_host: platform-qa.example.com
          ansible_user: fradmin
          depends_on:
            - access_management
            - identity_management
    
    platform_ui:
      hosts:
        ui-vm-qa:
          ansible_host: am-qa.example.com
          ansible_user: fradmin
          depends_on:
            - access_management
            - identity_management
            - identity_gateway

  vars:
    ansible_python_interpreter: /usr/bin/python3
    environment: qa
    vault_environment: qa

